//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bida
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBan
    {
        public int ChiTietHoaDonBanId { get; set; }
        public Nullable<int> IdHoaDonBan { get; set; }
        public Nullable<int> IdSanPham { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
