//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanBida
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int SanPhamId { get; set; }
        public string TenSanPham { get; set; }
        public int Soluong { get; set; }
    }
}
